### PR TITLE
apis: add omitempty to optional fields

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Very rough approximation of where necessary:

```
$ git grep -A 1 '+optional' | grep -v optional | grep -v omitempty | grep json
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
That home-brewed unstructured conversion is really annoying. Every time the type changes, that test breaks.

@ncdc need another LGTM

**Comment by stevekuznetsov** [comment]
@sttts @ncdc could use another LGTM

**Comment by sttts** [comment]
codegen

**Comment by stevekuznetsov** [comment]
WTF I am running it (clean) locally ...

**Comment by stevekuznetsov** [comment]
AH. Hoisted by my own petard. The files change, but the semantic meaning of the objects inside does not. Sigh.

**Pull request merged**
