### PR TITLE
🌱 Add make targets to update and verify go.mod

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
- Add `make modules` to run `go mod tidy` on the repo root and pkg/apis
- Add `make verify-modules` to ensure the everything is up to date

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
@stevekuznetsov @sttts @davidfestal do you want this as a separate Prow job (similar to boilerplate, codegen, etc.)? Or incorporate it into one of the existing ones?

Bigger question: should we consolidate any of these into a single Prow job / what are the pros/cons of having 1 job vs. many?
- lint
- codegen
- deps
- imports
- boilerplate
- test

**Comment by ncdc** [comment]
hooray for prow jobs getting killed
/retest

**Comment by stevekuznetsov** [comment]
They're just containers in the end, so there's really no overhead to more. I don't know that any of these is costly & hard to run, IMO the risk of a mega-job is re-doing too much work when something flakes, right?

**Comment by ncdc** [comment]
Ok, happy to update openshift-release to add a new job after this merges

**Pull request merged**
