### PR TITLE
:bug: Set worker count to 10 everywhere

### PR DESCRIPTION
**Pull request by mjudeikis**
## Summary

Taken from @sttts  who took it from @ncdc :D 

## Related issue(s)

Fixes #

## Release Notes

```release-note
Set worker count to 10
```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/lgtm

**Comment by sttts** [comment]
I believe I saw instability at the time. Needs debugging.

**Comment by dilipmighty245** [comment]
same for this as well : https://github.com/kcp-dev/kcp/pull/3093

**Pull request closed without merging**
