### PR TITLE
:sparkles: virtual/workspaces: allow configuring authorization cache resync

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 Container sidecar exited with code 137, reason OOMKilled 
```

!

**Comment by stevekuznetsov** [comment]
This flaked on #2263 - should be good to go once #2260 merges to make that skippable.

**Review by ncdc — APPROVED** [review]

**Comment by ncdc** [comment]
Retest when ready

**Pull request merged**
