### PR TITLE
Watch cache: use resource.group for object type in log messages and metrics

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Update kubernetes to pull in https://github.com/kcp-dev/kubernetes/pull/94:

> Update logging and metrics references to "object type" to be by "group
resource" instead, so the logs/metrics can disambiguate custom resource
types, instead of grouping them all together as
*unstructured.Unstructured.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
Looks like it worked. From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/1834/pull-ci-kcp-dev-kcp-main-e2e/1562848878393298944/artifacts/e2e/e2e/artifacts/TestAPIBinding/681238224/artifacts/kcp/shared/kcp.log:

```
I0825 17:30:23.795083   38167 cacher.go:432] cacher (cowboys.wildwest.dev): initialized
```

**Comment by stevekuznetsov** [comment]
k8s PR merged, good after we rebase on correct deps

**Comment by ncdc** [comment]
Updated

**Pull request merged**
