### PR TITLE
🐛 Fix the spec.URL in workspace using canonicalPath

### PR DESCRIPTION
**Pull request by qiujian16**
The spec.URL in workspace should use canonicalPath

## Summary
The spec.URL of workspace should use canonicalPath instead of absolute path.

## Related issue(s)

Fixes https://github.com/kcp-dev/kcp/issues/2737

### CODE REVIEW

**Comment by qiujian16** [comment]
/hold for testing
this is still need to be confirmed whether it is the appropriate approach.

**Comment by ncdc** [comment]
Code LGTM. @sttts does this violate any tenets for workspace URLs?

**Review by ncdc — APPROVED** [review]

**Pull request merged**
