### PR TITLE
Fix misspell words

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
## Related issue(s)

Fixes #
NONE

### CODE REVIEW

**Review by sttts — APPROVED** [review]

**Comment by sttts** [comment]
Needs `make codegen`.

**Comment by ArangoGutierrez** [comment]
> Needs `make codegen`.

I think `make codegen` is broken

```bash
./hack/update-codegen.sh
++ go env GOPATH
+ export GOPATH=/home/eduardo/go
+ GOPATH=/home/eduardo/go
++ dirname ./hack/update-codegen-clients.sh
+ SCRIPT_ROOT=./hack/..
++ cd ./hack/..
++ go list -f '{{.Dir}}' -m k8s.io/code-generator
+ CODEGEN_PKG=
+ bash /generate-groups.sh deepcopy,client,informer,lister github.com/kcp-dev/kcp/pkg/client github.com/kcp-dev/kcp/pkg/apis 'workload:v1alpha1 apiresource:v1alpha1 tenancy:v1alpha1 tenancy:v1beta1 apis:v1alpha1' --go-header-file ./hack/../hack/boilerplate/boilerplate.generatego.txt --output-base ./hack/.. --trim-path-prefix github.com/kcp-dev/kcp
bash: /generate-groups.sh: No such file or directory
make: *** [Makefile:73: codegen] Error 127
```
`go version go1.18 linux/amd64`

**Comment by ArangoGutierrez** [comment]
> Needs `make codegen`.

fixed

**Comment by sttts** [comment]
Oops, yet another rebase needed.

**Comment by ArangoGutierrez** [comment]
> Oops, yet another rebase needed.

done, rebased

**Comment by ArangoGutierrez** [comment]
Hoping for a merge before more rebasing ;P

**Pull request merged**
