### PR TITLE
virtualworkspace: fix delegated UPDATE semantics

### PR DESCRIPTION
**Pull request by stevekuznetsov**
When a user does an UPDATE while specifying a resourceVersion, we
absolutely need to be using that information in our delegated GET calls.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
 
/assign @sttts @ncdc

### CODE REVIEW

**Comment by sttts** [comment]
❤️

**Comment by sttts** [comment]
After a test as Andy says, lgtm.

**Comment by stevekuznetsov** [comment]
Looks like we pass the option down correctly to the delegated call even without this patch, so the failure is there anyway. I don't really want to think through the exact flow where this gets weird. Just to confirm - we are translating all Patch requests to the VW into UPDATE for the delegate, right?

**Comment by sttts** [comment]
> we are translating all Patch requests to the VW into UPDATE for the delegate, right?

yes

**Comment by stevekuznetsov** [comment]
/shrug

Did we do some survey to make sure that is correct in all cases? Seems like there might be some weirdness with it.

**Comment by ncdc** [comment]
Update can lead to data loss in certain situations:

1. Old client has old version of go struct
2. New field is added to the API
3. Instances in etcd have the new field
4. Old client gets an instance, makes some change, issues an update
5. New field is silently removed, because update is a wholesale replacement of the contents

**Comment by sttts** [comment]
This is using a dynamic client, doesn't it? No risk to lose anything, even with update.

**Comment by sttts** [comment]
New test failed again, have seen it at least twice in a row. Maybe it's real.

**Pull request closed without merging**
