### PR TITLE
:bug: syncer: use the correct key splitter

### PR DESCRIPTION
**Pull request by stevekuznetsov**
The status controller uses a cluster-unaware keyfunction, so it is not meaningful to use a cluster-aware splitter. Furthermore, there is no case in which the downstream informer will have cluster-aware keys.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Needed for #1958 
/assign @jmprusi 
/cc @ncdc

### CODE REVIEW

**Review by ncdc — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
/retest

```
 === Failed
=== FAIL: pkg/tunneler Test_integration_multiple_connections (2.62s)
2022/09/14 16:54:57 http: proxy error: EOF
2022/09/14 16:54:57 http: proxy error: EOF
    integration_test.go:121: Expected Hello world received 
    integration_test.go:121: Expected Hello world received 
```

**Comment by stevekuznetsov** [comment]
omg pls merge

**Pull request merged**
