### PR TITLE
✨ Add CustomResourceDefinitions as available for permission claims

### PR DESCRIPTION
**Pull request by hasheddan**
## Summary

Adds CustomResourceDefinitions as a type that can be included in permission claims in an APIExport for a virtual workspace.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

## Related issue(s)

n/a

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Ah, we are hitting https://github.com/kcp-dev/kcp/blob/f1971121fb8463c6dea3f047e0fe23e6e469df86/pkg/crdpuller/discovery.go#L497 here. Working on some updates 👍🏻

**Comment by ncdc** [comment]
@hasheddan did you get past the recursive schema issue?

**Comment by mjudeikis** [comment]
/close 
duplicate

**Pull request closed without merging**
