### PR TITLE
✨ Enable the SyncerTunnel featuregate by default

### PR DESCRIPTION
**Pull request by jmprusi**
## Summary

This PR enables the SyncerTunel feature-gate by default.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by davidfestal** [comment]
Do we still need the `privateKCPServer` if we're not using the feature flag anymore ?

**Comment by jmprusi** [comment]
> Do we still need the `privateKCPServer` if we're not using the feature flag anymore ?

Got rid of one in the second test, but on the first test it looks like I need to keep it to add the tokenFile, there's a way to get the same behaviour with Shared?

**Pull request merged**
