### PR TITLE
📖 Adopt CNCF Code of Conduct

### PR DESCRIPTION
**Pull request by embik**
## Summary

We are joining the CNCF as Sandbox project, and as such are subject to the CNCF CoC. I would suggest this PR as a way to adopting it and fulfil the onboarding requirement. 

## Related issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/cc @clubanderson @sttts @scheeles @mjudeikis @xrstf

I would like to get feedback from a major of maintainers before we go ahead with this change.

**Comment by embik** [comment]
/hold

until we have sufficient reviews.

**Comment by xrstf** [comment]
/approve

I approve of the idea, but cannot really judge the wording, as I don't know why we diverged from the CoC originally.

**Comment by embik** [comment]
> /approve
> 
> I approve of the idea, but cannot really judge the wording, as I don't know why we diverged from the CoC originally.

I do not believe we have diverged from the CNCF CoC at some point, but the CNCF CoC is a modernized version.

**Pull request merged**
