### PR TITLE
📖 Add rebase documentation

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Add documentation on the rebase process.

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]
This looks like all the highlights - nice write-up!

**Comment by xrstf** [comment]
This is great and will be an amazing help in the future :-)

**Comment by waltforme** [comment]
Maybe a dumb question: Why does kcp-dev/apimachinery `require`s k8s.io/api? Sounds like a 'reversed' dependency? Thanks!

**Comment by stevekuznetsov** [comment]
@waltforme I don't know where the `kcp-dev/apimachinery` name came from in the beginning, to be honest. It's not related to `k8s.io/apimachinery` and untangling it might be a good use of time. The contents in the repo are related like this:

- [`kcp-dev/apimachinery/pkg/cache`](https://github.com/kcp-dev/apimachinery/tree/main/pkg/cache) is similar to `k8s.io/client-go/tools/cache` [here](https://github.com/kubernetes/client-go/tree/master/tools/cache)
- [`kcp-dev/apimachinery/pkg/client`](https://github.com/kcp-dev/apimachinery/tree/main/pkg/client) is the machinery behind the cross-cluster clients generated by [`kcp-dev/code-generator`](https://github.com/kcp-dev/code-generator) and committed to [`kcp-dev/client-go`](https://github.com/kcp-dev/client-go)

Perhaps deleting the repo and subsuming the content into the more appropriate places would be good.

**Comment by waltforme** [comment]
I see. Now the dependency makes sense. Also it explains why the repository is so small.
Maybe I should take a closer look before asking this.
Thanks for the detailed explanations! @stevekuznetsov

**Pull request merged**
