### PR TITLE
:seedling: Simplify heartbeat controller

### PR DESCRIPTION
**Pull request by csams**
## Summary
- Remove the base controller as it was only used by the heartbeat controller
- Collapse the base controller into the heartbeat controller
- Simplify the heartbeat controller code and structure
- Update the heartbeat controller to use the committer package.

Signed-off-by: Christopher Sams <csams@redhat.com>

## Related issue(s)
#2635

### CODE REVIEW

**Comment by sttts** [comment]
This base controller has only one consumer. Why do we have it as separate package?

**Comment by ncdc** [comment]
If I had to guess, we probably kept moving consumers away until we were only left with 1, but never collapsed. I'll do that.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
