### PR TITLE
[0.6] Fix flaky informers

### PR DESCRIPTION
**Pull request by ncdc**
Like-port of #1649, pulling in https://github.com/kcp-dev/kubernetes/pull/86 which backports 85 onto feature-logical-clusters-1.23

### CODE REVIEW

**Comment by ncdc** [comment]
Backported the other commit from #1613 (one already was). Made a slight change (`wait.ForeverTestTimeout/30` --> `wait.ForeverTestTimeout`)

**Comment by ncdc** [comment]
Was all green. Please review backport-ish commit

**Comment by sttts** [comment]
Worth v0.6.4.

**Comment by ncdc** [comment]
Agreed, will do

**Comment by ncdc** [comment]
Done

**Pull request merged**
