### PR TITLE
go get was deprecated and no longer works with 1.18

### PR DESCRIPTION
**Pull request by aojea**
see https://go.dev/doc/go-get-install-deprecation

### CODE REVIEW

**Comment by aojea** [comment]
things of having go1.18 as default in your host XD

**Comment by marun** [comment]
Maybe update `contrib/crds/generate-crds.sh:37:    go get sigs.k8s.io/controller-tools/cmd/controller-gen` too for completeness?

**Comment by aojea** [comment]
> controller

yep

**Comment by marun** [comment]
Please squash - no need for multiple commits here - and I'll merge

**Comment by aojea** [comment]
> Please squash - no need for multiple commits here - and I'll merge

done

**Review by marun — APPROVED** [review]

**Pull request merged**
