### PR TITLE
✨ Update to Kubernetes 1.26.3

### LINKED ISSUE #2772: ✨ Rebase to Kubernetes 1.26
Links:
- [1.24 branch commit tracking spreadsheet](https://docs.google.com/spreadsheets/d/1pKfe1dICl65ST-r05MVwoc6nGDvUT0wTQ-rLcSfjPQo/edit#gid=0)
- [Pre-rebase prep branch](https://github.com/ncdc/kubernetes/tree/kcp-1.26-rebase-prep) (squashing as much as possible to minimize rebase effort; force-pushes will be frequent)

```[tasklist]
### Tasks
- [ ] https://github.com/kcp-dev/code-generator/pull/80
- [ ] Update our apimachinery to 1.26
- [ ] Update our client-go to 1.26
```

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Update to Kubernetes 1.26.3.

## Todos
- [x] Unit tests pass
- [x] Boilerplate
- [x] Lint
- [ ] Update go.mod to real Kube branch
- [x] Enable ValidatingAdmissionPolicy

## Related issue(s)

Fixes #2772

### CODE REVIEW

**Comment by ncdc** [comment]
@MikeSpreitzer no need to retest. The code isn't ready for merging. Still working on finding the source of some issues.

**Comment by ncdc** [comment]
Looks like presubmits are running on build01 now... maybe it'll have more cpu 🤷 

/retest

**Comment by ncdc** [comment]
Status update:
* The rebase work is "done" in the sense that everything has been updated and it all compiles
* It looks like there is a performance regression and possibly a [behavioral regression](https://kubernetes.slack.com/archives/C021U8WSAFK/p1684143928808069?thread_ts=1684143903.932469&cid=C021U8WSAFK)
* I am working on other things now, and could really use help from others to diagnose the remaining issues to help get this done
* One of the commits in my branch increases the number of worker goroutines for most/all controllers to 10. We saw an issue with this pre-rebase where the deletion e2es were not completing in time. We're still seeing that in the rebase. We potentially could drop this commit, although it would be nice to determine the root cause of this issue.

**Comment by sttts** [comment]
`go test ./test/e2e/reconciler/workspacedeletion/ -v -count 1 -args --use-default-kcp-server` alone run locally just takes the same time: 12s, although timing out in prow.

**Comment by sttts** [comment]
```
E0517 13:54:58.152639   42432 logicalcluster_deletion_controller.go:225] deletion of logical cluster 2iu62bs2xhxnhfhq|cluster failed: some content remains in the logical cluster, estimate 5 seconds before it is removed: Some resources are remaining: apibindings.apis.kcp.io has 1 resource instances; Some content in the logical cluster has finalizers remaining: apis.kcp.io/apibinding-finalizer in 1 resource instances
```

This looks fishy.

**Comment by ncdc** [comment]
Yes, many of these tests time out in CI but not locally.

Another thing I noticed running locally: ran the quota e2e. It passed. Checked etcd. There were still a small handful of CRs (sheriffs or cowboys, can't remember which) but the CRDs/schemas/exports/bindings/workspaces/logicalclusters - everything related to the test - had all been deleted. Because we never did a test to verify all content was deleted, I have no way of knowing if this is a regression or it's always been that way.

**Comment by sttts** [comment]
Thanks to GPT-4 writing a script, here are the files in the logs that change most (% number in last column):
```
labelclusterrolebinding_controller.go 23995 202512 -157,626
logicalcluster_resource_deletor.go 741 2533 -109,469
workspace_reconcile_deletion.go 327 1023 -103,111
graph_builder.go 80571 32612 84,7459
workspace_reconcile_phase.go 3724 1785 70,3939
resource_quota_monitor.go 100594 53081 61,8357
informer.go 22115 14343 42,6354
garbagecollector_patch.go 21653 14898 36,9621
resource_quota_controller_patch.go 10893 7532 36,483
shared_informer.go 34637 24698 33,5013
resource_quota_controller.go 1923 1395 31,8264
apiexport_controller.go 1274 930 31,216
logicalcluster_deletion_controller.go 5573 7525 -29,8061
apibinding_controller.go 40111 29892 29,1959
reflector.go 1315 987 28,497
labelclusterrolebinding_reconcile.go 3501 2639 28,0782
statusless_committer.go 3750 2836 27,7558
workspace_controller.go 11578 8770 27,5998
bootstrap_reconcile.go 888 681 26,3862
replication_reconcile.go 5831 4645 22,6422
bootstrap.go 1088 872 22,0408
labellogicalcluster_reconcile.go 277 224 21,1577
apiexport_apireconciler_controller.go 1856 1516 20,1661
apiexport_apireconciler_reconcile.go 715 590 19,1571
apibindingannotation_controller.go 26255 22282 16,371
committer.go 23959 20925 13,5193
apibinding_deletion_controller.go 10983 9596 13,4798
defaultlocation_controller.go 556 487 13,2311
synctargetexports_controller.go 807 707 13,21
heartbeat_controller.go 875 769 12,8954
synctarget_controller.go 1041 928 11,4779
workspacetype_controller.go 239 217 9,64912
labelclusterrole_controller.go 110452 100791 9,14681
syncer_apireconciler_controller.go 656 599 9,08367
permissionclaimlabel_resource_reconcile.go 4294 3926 8,95377
apibinder_initializer_reconcile.go 6943 6392 8,26397
syncer_apireconciler_reconcile.go 6945 6424 7,79415
placement_controller.go 2078 1932 7,2818
controller.go 11017 10291 6,81434
cacher.go 892 834 6,72074
decorator.go 2487 2327 6,64728
publisher.go 1891 1782 5,9352
apibinder_initializer_controller.go 10361 9773 5,84087
garbagecollector.go 1258 1190 5,55556
labellogicalcluster_controller.go 34548 36446 -5,34693
workspace_reconcile_scheduling.go 1833 1739 5,26316
```

**Comment by clubanderson** [comment]
@MikeSpreitzer you want to have a closer look at the CI regression issue here that is holding up the 1.26 rebase?  If we clear this hurdle then we can close out on the rebase backlog issue in kubestellar.

**Comment by sttts** [comment]
See my debug PR https://github.com/kcp-dev/kcp/pull/2956. We are near.

**Comment by ncdc** [comment]
Superseded by #2956 

/close

**Pull request closed without merging**
