### PR TITLE
Move misspell and gofmt into golangci-lint config

### PR DESCRIPTION
**Pull request by imjasonh**
Import checking is already covered by `make verify-codegen`

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@imjasonh this has a conflict, otherwise LGTM

**Comment by stevekuznetsov** [comment]
@imjasonh did you want to rebase this one?

**Review by ncdc — APPROVED** [review]

**Comment by ncdc** [comment]
Going to have to remove gofmt as a required status 😄

**Comment by ncdc** [comment]
Done!

**Pull request merged**
