### PR TITLE
ci: update to actions/upload-artifact@v3

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Looks fine, but this lacks enough context for me to be confident in merging it

**Comment by sttts** [comment]
> Looks fine, but this lacks enough context for me to be confident in merging it

v3 > v2. Must be better.

But seriously: we see 500 errors with v2 constantly. It's a known problem with github issues that got closed, but apparently not fixed. Others see it too. My hope is that the developers just moved on with v3 and that is better. We have a third-party upload retry action now. Looks like it works better.

**Review by stevekuznetsov — APPROVED** [review]

**Comment by ncdc** [comment]
@sttts do you want to keep dependabot enabled / did you mean to delete the file for it?

**Comment by sttts** [comment]
> do you want to keep dependabot enabled / did you mean to delete the file for it?

Have never used it. Any experience? Works well?

**Comment by ncdc** [comment]
It opened the bump PRs from before. Seemed good

**Pull request merged**
