### PR TITLE
:sparkles:  Install Calico in kind for CI testing

### PR DESCRIPTION
**Pull request by lionelvillard**
## Summary

Default kind configuration does not support network policies. This PR modifies the kind configuration disabling kindnet and install Calico.

## Related issue(s)

/cc @davidfestal

### CODE REVIEW

**Comment by davidfestal** [comment]
Do you think you could upgrade the `kind` version to `0.17.0` at the same time ?
It is done in [another PR](https://github.com/kcp-dev/kcp/pull/2336/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR45), but it seems to me that this kind version upgrade fits better in this PR.

**Review by davidfestal — COMMENTED** [review]
Commented about adding an upgrade of the kind version in this PR.

**Comment by lionelvillard** [comment]
TestDeploymentCoordinator "flake"

/test-required

**Comment by davidfestal** [comment]
> TestDeploymentCoordinator "flake"
> 
> /test-required

TBF it seems more than a flake here, since it never succeeds. Wondering if something in the change breaks them.

**Comment by davidfestal** [comment]
@stevekuznetsov So do you confirm it is OK for you if we still merge this PR and @lionelvillard would create a follow-up PR for the changes you requested in this slack thread: https://kubernetes.slack.com/archives/C021U8WSAFK/p1672913451512589 ?

**Comment by davidfestal** [comment]
> @stevekuznetsov So do you confirm it is OK for you if we still merge this PR and @lionelvillard would create a follow-up PR for the changes you requested in this slack thread: https://kubernetes.slack.com/archives/C021U8WSAFK/p1672913451512589 ?

I assume yes, as you mentioned here https://kubernetes.slack.com/archives/C021U8WSAFK/p1672931932256269?thread_ts=1672913451.512589&cid=C021U8WSAFK

Let me approve then.

**Pull request merged**
