### PR TITLE
apis/apis: allow apis.kcp.dev claims without identity

### PR DESCRIPTION
**Pull request by sttts**
apis.kcp.dev does not have an identity.

### CODE REVIEW

**Review by shawn-hurley — COMMENTED** [review]
Probably could add some test cases for these updates? 

Otherwise LGTM

**Comment by sttts** [comment]
Will come with https://github.com/kcp-dev/kcp/pull/1563. Maybe let's wait for that.

**Comment by ncdc** [comment]
The work @robinbobbitt is doing for #1544 might result in us needing to remove this CEL validation entirely, or generate it... maybe worth a discussion

**Comment by sttts** [comment]
Not sure we have to remove it or can extend it. But I agree that the value is limited.

**Comment by sttts** [comment]
Leaving as part of https://github.com/kcp-dev/kcp/pull/1563.

**Pull request closed without merging**
