### PR TITLE
test smd update

### PR DESCRIPTION
**Pull request by aojea**
test smd update 

https://github.com/kcp-dev/kubernetes/pull/91

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@aojea this seems to have broken the metadata mutation test - can you make sure your k8s PR does not get rid of Andy's DeepCopy?

**Comment by stevekuznetsov** [comment]
Hm, nevermind, it's just a vendor bump ...

/retest

**Comment by stevekuznetsov** [comment]
It reproduces, and only on this PR. Wild.

**Comment by aojea** [comment]
first time I do this dance , most probably I've done something wrong

**Comment by stevekuznetsov** [comment]
@aojea I think you did the PR to `kcp-dev/kubernetes` and `kcp-dev/kcp` correctly, but it seems like something in this bump breaks the test.

**Comment by ncdc** [comment]
The branch is missing my commit - see https://github.com/kcp-dev/kubernetes/pull/91#issuecomment-1225833305

**Comment by ncdc** [comment]
#1799 did this directly to the kcp go.mod - closing
/close

**Pull request closed without merging**
