### PR TITLE
*: remove the vestigial attempt at cross-shard resourceversions

### PR DESCRIPTION
**Pull request by stevekuznetsov**
With this code removed we can remove the commits in our Kubernetes fork
that are required to support it, thereby reducing our rebase burden.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @sttts @ncdc

### CODE REVIEW

**Comment by sttts** [comment]
Nvmd, was misreading. I thought this is a kube PR.

**Comment by stevekuznetsov** [comment]
This code is not imported by any other part of the system, it's a waste of time and resources to try to "deflake" these tests.

**Pull request merged**
