### PR TITLE
🐛 syncer/status: make sure the resource is owned by this syncer before updating the status

### PR DESCRIPTION
**Pull request by jmprusi**
## Summary

The syncer Status controller was missing a validation check, so it could update the wrong resource status field in certain cases.

## Related issue(s)

Fixes https://github.com/kcp-dev/kcp/issues/2048

### CODE REVIEW

**Comment by jmprusi** [comment]
@sttts, can you force the merge without considering the lint test? It's complaining about the structured logging, which this PR has nothing to do with, and there's another PR where the conversion to structured logging is handled. Thanks!

**Comment by ncdc** [comment]
@jmprusi please follow the instructions re lint:
```
[INFO] If you need to update the saved list, run `make update-contextual-logging` and commit `hack/logcheck.out`'
```

Thanks!

**Comment by jmprusi** [comment]
@ncdc fixed! thanks!

**Review by davidfestal — APPROVED** [review]

**Comment by davidfestal** [comment]
@ncdc Unholded the PR since lint errors have been fixed.

**Pull request merged**
