### PR TITLE
:book: Update release process with release note generation

### PR DESCRIPTION
**Pull request by embik**
## Summary

This PR is to propose a change in our release process, namely the release note generation. So far, we have relied on the GitHub auto-generated release notes, but we implemented all the tooling via Prow to use Kubernetes release note generation. I've tested this process in anticipation of the upcoming kcp 0.22.0 release and this seems to work fine, so I think we should change this to have a more meaningful changelog.

## Related issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

for enough time to discuss this proposal.

**Comment by mjudeikis** [comment]
+1 on the change. Quite straight forward. 
@sttts wdyt?

**Comment by sttts** [comment]
Am fine with whatever is convenient and looks ok.

/approve

**Comment by embik** [comment]
FYI, I forgot to document the need for a GitHub API token. Added the following now:

> To use `release-notes` you will need to generate a GitHub API token (Settings -> Developers settings -> Personal access tokens -> Fine-grained tokens). A token with _Public Repositories (read-only)_ repository access and no further permissions is sufficient. Store the token somewhere safe and export it as `GITHUB_TOKEN` environment variable.

Let me know if that changes your perception of the change. Otherwise, I'm happy to go ahead and merge this.

/hold cancel

**Pull request merged**
