### PR TITLE
🐛 tmc e2e: fix Syncer virtual workspace e2e test flakes

### PR DESCRIPTION
**Pull request by davidfestal**
## Summary

TMC E2E: Attempt at fixing Syncer virtual workspace e2e test flakes.
Not sure it would fix them all, but at east it fixes a possible cause, and increases log details (through the use of `framework.Eventually` instead of `require.Eventually`

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by davidfestal** [comment]
re-running the e2e tests several times to checks for flakes.

**Comment by davidfestal** [comment]
@ncdc if the tests pass again this time would you approve ?

**Review by ncdc — APPROVED** [review]

**Pull request merged**
