### PR TITLE
:warning: Remove TMC bootstrap assets

### PR DESCRIPTION
**Pull request by mjudeikis**
## Summary

Removes Locations, Placement, Synctarget related API resources from bootstrap process to avoid unmanaged APIS being present.

part of https://github.com/kcp-dev/kcp/issues/2954 

```release-note
Remove TMC APIS from bootstrap process
```

## Related issue(s)
Fixes #

 Signed-off-by: mjudeikis mangirdas@judeikis.lt

### CODE REVIEW

**Comment by mjudeikis** [comment]
@xrstf @sttts would like some rubber stamp on this :)

**Review by xrstf — APPROVED** [review]
/lgtm

**Pull request merged**
