### PR TITLE
:seedling: Remove ingress splitter and deployment splitter which do not work currently...

### PR DESCRIPTION
**Pull request by davidfestal**
## Summary

Remove ingress splitter and deployment splitter since they currently do not work
and should be reimplemented based on
coordination controllers.

### CODE REVIEW

**Comment by ncdc** [comment]
There's also an e2e for ingress

**Comment by ncdc** [comment]
Will need to update contextual logging

**Comment by davidfestal** [comment]
> There's also an e2e for ingress

Let's remove it also since anyway it is broken:
```
				//
				//
				// Here, the ingress test stop working because the ingresssplitter controller looks for
				// ingress objects in kcp without taking the identity into consideration. We have to lift
				// ingressplitter be negotiation workspace aware, and while doing that probably also move
				// to vw-based transformations.
				//
				//
				return
```

**Pull request merged**
