### PR TITLE
move Config to separate file

### PR DESCRIPTION
**Pull request by deitch**
## Summary

Move `Config`, `CompletedConfig` and the related parts from `server.go` to `config.go`

No code change, just file split to make it easier to consume and reason about. As discussed with @sttts

### CODE REVIEW

**Comment by deitch** [comment]
boilerplate is fine this time, ready for a full retest @sttts

**Comment by deitch** [comment]
@sttts any idea why these tests failed?

**Comment by sttts** [comment]
> any idea why these tests failed?

We have some flakes, something around watches and events.

**Comment by sttts** [comment]
/override ci/prow/e2e-multiple-runs

This is pure move, and rebase is painful. Hence....

**Pull request merged**
