### PR TITLE
Change issue template to newer issue forms

### LINKED ISSUE #610: Change issue template to newer issue forms
**Is your feature request related to a problem? Please describe.**
This project uses old Issue templates and currently has no pull request templates.  

**Describe the solution you'd like**
- Upgrade issue template to newer issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

### PR DESCRIPTION
**Pull request by avinal**
## Summary

Change issue template to newer issue forms. See screenshots
1. Feature Request
image
2. Epic Request
image
3. Community Meeting Agenda
image
4. Bug Report
image

## Related issue(s)
- Fixes #610

Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

### CODE REVIEW

**Comment by sttts** [comment]
Is there still a free-form variant too after this PR ? How do the issues look like after filling in those text fields?

**Comment by avinal** [comment]
> Is there still a free-form variant too after this PR ? How do the issues look like after filling in those text fields?

Hello Stefan, No free form variant after this PR, I converted them all to newer forms. The final form of the issue is markdown only. The forms only ensure that the required fields are never skipped and enhance readability. Here is an example for Feature Request.

image

You can test all of them here: https://github.com/avinal/experiment2/issues/new/choose

**Comment by avinal** [comment]
There is no such thing for PR yet, we can improve the existing one though.

**Comment by sttts** [comment]
How many of our PRs actually use the template? :)

**Comment by sttts** [comment]
At least you can edit the markdown freely after creation.

**Comment by avinal** [comment]
Hello @ncdc, @sttts is there anything else left to do in this PR?

**Pull request merged**
