### PR TITLE
🐛 bug fix Add maximal permission policy for compute APIExport

### PR DESCRIPTION
**Pull request by qiujian16**
Signed-off-by: Jian Qiu <jqiu@redhat.com>

## Summary
the root:compute kubernetes APIExport should add maximal permission policy RBAC.

## Related issue(s)

Fixes https://github.com/kcp-dev/kcp/issues/1959

### CODE REVIEW

**Comment by kasturinarra** [comment]
@qiujian16 one question, what is this change about and why are we adding this ?

**Comment by qiujian16** [comment]
this is to ensure the APIBinding for kubernetes APIExport in root:compute workspace can be consumed. See the doc here https://github.com/kcp-dev/kcp/blob/main/docs/syncer.md#select-resources-to-sync

**Comment by kasturinarra** [comment]
@qiujian16 thanks, adding the right link here https://github.com/kcp-dev/kcp/blob/main/docs/content/en/main/concepts/syncer.md#select-resources-to-sync

**Pull request merged**
