### PR TITLE
Added ppc64le and arm64 support to the Syncer image

### PR DESCRIPTION
**Pull request by mayurwaghmode**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by mayurwaghmode** [comment]
@sttts @ncdc Can u please review the PR?

**Review by sttts — APPROVED** [review]

**Comment by mayurwaghmode** [comment]
@ncdc can u please review the PR?
@sttts are we good about merging this PR?

**Comment by mayurwaghmode** [comment]
@sttts have created a fresh PR here for adding the PPC64LE and ARM64 support to the Syncer image - https://github.com/kcp-dev/kcp/pull/1235

**Pull request closed without merging**
