### PR TITLE
runDemoScripts.sh L#111

### PR DESCRIPTION
**Pull request by IshanSakhuja**
In line #111 there is an error of go syntax of '(' 

Error - line 111: syntax error near unexpected token `('

### CODE REVIEW

**Comment by ncdc** [comment]
What bash version do you have?

**Comment by IshanSakhuja** [comment]
3.2.57(1)-release

**Comment by ncdc** [comment]
Can you upgrade to 4+ (if on a Mac, `brew install bash` via Homebrew)?

**Comment by IshanSakhuja** [comment]
Sure I just checked the version my bad.

**Pull request closed without merging**
