### PR TITLE
kcp CLI: error out for an non existent workspace while changing ws

### LINKED ISSUE #1190: `kubectl kcp ws ju:nk` succeeds to create bad state
**Describe the bug**
The `kubectl kcp ws` subcommand will accept a workspace argument that is nonsense if it contains a colon, leading to a state that is difficult to recover from.

**To Reproduce**
1. Start with `Current workspace is "root".`
2. `kubectl kcp ws junk` .  Observe `error: clusterworkspaces.tenancy.kcp.dev "junk" not found`
3. `kubectl kcp ws ju:nk` .  Observe `Current workspace is the URL "https://1.2.3.4:6443/clusters/ju:nk`.  But there is not really any such thing.
4. `kubectl kcp ws ..` .  Observe `error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace`.
5. `kubectl kcp ws root:default` .  Observe `error: current URL "https://1.2.3.4:6443/clusters/ju:nk" does not point to cluster workspace`.

**Expected behavior**
Invalid input is rejected even if it contains a colon.

**Additional context**
current `main`, commit 62dd95ce10e7cdefc502129414e60b4a52a79aa0

### PR DESCRIPTION
**Pull request by sm43**
previously, cli used to proceed creating bad state even
if the workspace doesn't exist on the cluster.
now, it validate the workspace if it exist on the cluster.

Fixes #1190

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>\

Changes applied on cluster:
Current workspaces in the cluster
```
 > ~ > k kcp ws
Current workspace is "root".
 > ~ > k kcp ws list
NAME      TYPE           PHASE   URL
default   Organization   Ready   https://10.76.98.68:6443/clusters/root:default
green     Organization   Ready   https://10.76.98.68:6443/clusters/root:green
 > ~ > k kcp ws use green
Current workspace is "root:green" (type "Organization").
 > ~ > k kcp ws list
NAME   TYPE        PHASE   URL
g1     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g1
g2     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g2 > ~ > k kcp ws
Current workspace is "root".
 > ~ > k kcp ws list
NAME      TYPE           PHASE   URL
default   Organization   Ready   https://10.76.98.68:6443/clusters/root:default
green     Organization   Ready   https://10.76.98.68:6443/clusters/root:green
 > ~ > k kcp ws use green
Current workspace is "root:green" (type "Organization").
 > ~ > k kcp ws list
NAME   TYPE        PHASE   URL
g1     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g1
g2     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g2
```

CLI output for invalid workspaces
```
 > ~ > k kcp ws junk
error: clusterworkspaces.tenancy.kcp.dev "junk" not found
 > ~ > k kcp ws ju:nk
error: invalid workspace name format: ju:nk
 > ~ > k kcp ws root:abc
error: clusterworkspaces.tenancy.kcp.dev "abc" not found
 > ~ > k kcp ws root:green:g3
error: workspaces.tenancy.kcp.dev "g3" not found
 > ~ > k kcp ws
Current workspace is "root".
 > ~ > k kcp ws root:default
Current workspace is "root:default".
```

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why should we do this in the CLI plugin as opposed to the admission chain in the server? If we send back useful error messages, all clients should be able to surface them.

**Comment by stevekuznetsov** [comment]
I see, sorry - when I read that the validation was telling someone about an invalid format, I thought we were creating workspaces. In my mind, the check to see if a workspace exists is sufficient - if it's an invalid format, it won't exist. Since the user is not trying to create a new workspace, it's not as important to tell them about formats that can be valid.

**Review by stevekuznetsov — COMMENTED** [review]
I'm not sure exactly what the pretty-name failure is about, but @davidfestal will be able to help you.

**Comment by sm43** [comment]
@sttts  @davidfestal I have addressed the comments ptal :)

I am trying to add unit test but one of the current tests is failing 
more details  https://github.com/kcp-dev/kcp/pull/1278#issuecomment-1157660387
if you could help me understand the use of `prettyNames` in the test

**Comment by sttts** [comment]
Perfect.

/lgtm
/approve
/ok-to-test

**Comment by sttts** [comment]
Unit test broken.

**Comment by sm43** [comment]
> Unit test broken.
@sttts 
yeah. I am not sure how to handle `TestUse/absolute name` Test
It is trying to find `bar` workspace (`root:foo:bar`)
but here https://github.com/kcp-dev/kcp/blob/060f5ec825c777c190cf27518ec33be1b8ea88a7/pkg/cliplugins/workspace/plugin/kubeconfig_test.go#L337 
prettyNames is replacing `{"bar": "baz"}`
can you tell how can I fix this?

**Comment by sttts** [comment]
The pretty names go away soon. Doens't it help to just make that pretty-name map empty?

**Comment by sm43** [comment]
> The pretty names go away soon. Doens't it help to just make that pretty-name map empty?

@sttts yep. Thanks. it does fixes it. added a couple of more tests. ptal :)

**Pull request merged**
