### PR TITLE
🌱 kcp: controllers don't have to check if caches have been synced during startup

### PR DESCRIPTION
**Pull request by p0lyn0mial**
## Summary
This requirement is enforced by the `waitForSync` method.
All controllers must be gated on that method before they are run.

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by stevekuznetsov — COMMENTED** [review]
What was the reason we didn't do this everywhere in the first place?

**Comment by ncdc** [comment]
This is covered by https://github.com/kcp-dev/kcp/blob/3c4e7937b80aac7b2f20878393e957417702969a/pkg/server/controllers.go#L1107

**Comment by ncdc** [comment]
s.syncedCh is closed when all informers are synced

**Comment by p0lyn0mial** [comment]
> s.syncedCh is closed when all informers are synced

okay, but I think that:

- controllers should be self-contained
- this is now how a standard controller looks like
- this is non-intuitive, for example, [this controller](https://github.com/kcp-dev/kcp/blob/3c4e7937b80aac7b2f20878393e957417702969a/pkg/reconciler/kubequota/kubequota_controller.go#L95) accepts `informersStarted <-chan struct{}` (`s.syncedCh`) but also waits for `crdInformer.Informer().HasSynced` or [the bootstrap controller](https://github.com/kcp-dev/kcp/blob/cf0235c3cc51e8eae17981ebca0424200ab8c3c4/pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go#L77) that waits for `workspaceInformer.Informer().HasSynced`

**Comment by ncdc** [comment]
> controllers should be self-contained

This is the key point up for discussion I'd say. @sttts & I made a decision a while ago to do it the way you currently see in the repo. I am happy to discuss if we want to change the approach.

> this is non-intuitive, for example, [this controller](https://github.com/kcp-dev/kcp/blob/3c4e7937b80aac7b2f20878393e957417702969a/pkg/reconciler/kubequota/kubequota_controller.go#L95) accepts informersStarted <-chan struct{} (s.syncedCh)

This is a one-off requirement of the Kubernetes quota controller. Now that I think about it, since we don't start any quota delegates until after s.syncedCh is closed, we could remove passing it in, and instead pass an always-closed channel when creating delegate controllers.

> but also waits for crdInformer.Informer().HasSynced

I don't recall the specifics, but I think I ran into some issues... we could try removing this and see what happens. Maybe I missed putting in the waitForSync originally, added the specific crdInformer check, and never went back to remove it.

> or [the bootstrap controller](https://github.com/kcp-dev/kcp/blob/cf0235c3cc51e8eae17981ebca0424200ab8c3c4/pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go#L77) that waits for workspaceInformer.Informer().HasSynced

It's probably safe to remove this.

**Comment by p0lyn0mial** [comment]
Ok, updated the PR.

The only controller that makes use of the `HasSynced` method is `ResourceController`. I think it is okay since it uses `DynamicDiscoverySharedInformerFactory`.

**Pull request merged**
