### PR TITLE
ci: turn off GitHub CI for jobs we run in Prow

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Part of #324 
/assign @ncdc @sttts

### CODE REVIEW

**Review by sttts — DISMISSED** [review]

**Comment by sttts** [comment]
What is special about the shared server one?

**Comment by stevekuznetsov** [comment]
@sttts shared server requires that I get the actual running of it figured out reproducibly from `make` and the images wired through etc. Runtime should be 10000% tunable based on how many resources we give the jobs.

**Comment by sttts** [comment]
Ack. I think we can move forward here, but would like to see the multiple-run job to be below 20min. Now it's 35min or so, much more than the others.

**Comment by ncdc** [comment]
/lgtm
/approve

c'mon tide 😄

**Comment by ncdc** [comment]
Manually merging

**Pull request merged**
