### PR TITLE
Switch to cluster name annotation

### PR DESCRIPTION
**Pull request by ncdc**
## Summary
Stop using ZZZ_DeprecatedClusterName and switch to cluster name via an annotation.

Depends on:
- [X] https://github.com/kcp-dev/logicalcluster/pull/21
- [X] https://github.com/kcp-dev/apimachinery/pull/49
- [x] https://github.com/kcp-dev/kubernetes/pull/87

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]

**Comment by ncdc** [comment]
Assuming the tests are looking good, I'll close #1674 to unblock the merge queue

**Pull request merged**
