### PR TITLE
:sparkles: enable shard scheduling and fix e2e tests

### PR DESCRIPTION
**Pull request by sttts**
Switching on random scheduling of workspaces to shards.

The current state of e2e tests:

✅ apibinding
:white_check_mark:  audit
✅ authorizer
:white_check_mark:  cache
:white_check_mark: test/e2e/conformance (@fgiloux https://github.com/sttts/kcp/pull/14 - the fix pulled into this PR)
:white_check_mark:  customresourcedefinition
:white_check_mark:  garbagecollector (@p0lyn0mial: Originally reported as `red` but after running it a few times on my local machine and examining [a CI run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/2596/pull-ci-kcp-dev-kcp-main-e2e-shared/1615003616358174720) I moved to `green`)
:white_check_mark:  homeworkspaces
:white_check_mark: test/e2e/watchcache (flakes, @p0lyn0mial, fixed by: https://github.com/kcp-dev/kcp/pull/2632)
:white_check_mark:   workspacetype
:white_check_mark:  reconciler/apiexport
:white_check_mark:  reconciler/cache (@p0lyn0mial, fixed by: https://github.com/kcp-dev/kcp/pull/2620)
:white_check_mark: test/e2e/reconciler/workspace (@p0lyn0mial, fixed by: https://github.com/kcp-dev/kcp/pull/2639)
✅ quota
✅  reconcilder/*
✅  virtual/*

~~:red_circle:  quota (@ncdc)~~
~~:red_circle: apibinding~~
~~:red_circle:  authorizer, flakes (@sur)~~
⚫ skipped: test/e2e/reconciler/locationworkspace (@p0lyn0mial, temporal fix in https://github.com/kcp-dev/kcp/pull/2650)
⚫ skipped: test/e2e/reconciler/scheduling (@p0lyn0mial, temporal fix in https://github.com/kcp-dev/kcp/pull/2651)
⚫ skipped: test/e2e/reconciler/cluster (@p0lyn0mial, temporal fix in https://github.com/kcp-dev/kcp/pull/2657)
⚫ skipped: test/e2e/recocniler/namespace (@p0lyn0mial, temporal fix in https://github.com/kcp-dev/kcp/pull/2658)
⚫ skipped: test/e2e/syncer (@p0lyn0mial, temporal fix in https://github.com/kcp-dev/kcp/pull/2652)
~~:red_circle: test/e2e/virtual/apiexport (@p0lyn0mial/@sur, opened https://github.com/kcp-dev/kcp/pull/2641 but I think that more fixes are required)~~
~~:red_circle: test/e2e/virtual/initializingworkspaces (@p0lyn0mial, opened https://github.com/kcp-dev/kcp/pull/2660 but we need more fixes)~~

some useful commands:

to run `apibinding` e2e tests against a multi-shard environment:
```
go test ./test/e2e/apibinding/ -v -p 1 -parallel 1 -v -failfast -count 1 -args --use-default-kcp-server --root-shard-kubeconfig=./.kcp-0/admin.kubeconfig
rm -r .kcp*; go run ./cmd/sharded-test-server --v=4 --number-of-shards=3 --shard-v=4
```

to run all e2e tests on a multi-shard environment:
```
rm -rf .kcp .kcp* artifacts; ARTIFACT_DIR=$PWD/artifacts UNSAFE_E2E_HACK_DISABLE_ETCD_FSYNC=true E2E_PARALLELISM=8 COUNT=1 SHARDS=3 make test-e2e-sharded-minimal WHAT=./test/e2e/...
```

to find out what is replicated into the cache and when:
```
tail -f .kcp-*/kcp.log | egrep 'replication_reconcile.go'
```

### CODE REVIEW

**Comment by fgiloux** [comment]
@sttts @p0lyn0mial it seems that [the commit for ValidatingWebhook](https://github.com/sttts/kcp/pull/14/commits/cd7631fbafc4ab3457b4839afcb040b64b6e6f64) is not in the PR anymore. Is it intentional?

**Comment by p0lyn0mial** [comment]
> @sttts @p0lyn0mial it seems that [the commit for ValidatingWebhook](https://github.com/sttts/kcp/pull/14/commits/cd7631fbafc4ab3457b4839afcb040b64b6e6f64) is not in the PR anymore. Is it intentional?

I don't think so, @sttts please pull that commit into this PR. Thanks!

**Comment by p0lyn0mial** [comment]
`ci/prow/e2e-sharded` is green!

can we merge this PR?

**Pull request merged**
