### PR TITLE
🌱 Enable KUBE_CACHE_MUTATION_DETECTOR in e2e tests

### LINKED ISSUE #1134: Enable cache mutation detector when running tests
- set `KUBE_CACHE_MUTATION_DETECTOR=1` when running at least e2e tests
- need to do it for the shared server launched in the e2e-shared-server job
- need to do it for private kcp server's launched by the e2e framework

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@redhat.com>

## Related issue(s)

Fixes #1134

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 test/e2e/framework/kcp.go:194:66: not enough arguments in call to require.NoError
	have (error)
	want (require.TestingT, error, ...interface{}) (typecheck)
			require.NoError(os.Setenv("KUBE_CACHE_MUTATION_DETECTOR", "1"))
			                                                              ^ 
```

**Comment by stevekuznetsov** [comment]
```
        CACHE *v1.ClusterRole[91] ALTERED!
        (*v1.ClusterRole)(0xc0020b7b80)({                                                       (*v1.ClusterRole)(0xc0020b7cc0)({
         TypeMeta: (v1.TypeMeta) {                                                               TypeMeta: (v1.TypeMeta) {
          Kind: (string) "",                                                                      Kind: (string) "",
          APIVersion: (string) ""                                                                 APIVersion: (string) ""
         },                                                                                      },
```

:boom:

**Comment by vincepri** [comment]
Last failure before rebasing: https://github.com/kcp-dev/kcp/actions/runs/3904111816/jobs/6669440017

**Pull request merged**
