### PR TITLE
🐛 Use my system:admin fix to kube

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR is for testing https://github.com/kcp-dev/kubernetes/pull/135 .
This is not intended to be merged as is, we want to merge an updated ref to kcp-dev/kubernetes after the fix there merges.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
And the ci/prow/deps job correctly points out that this PR switches to a kubernetes fork in an unexpected place.

**Comment by MikeSpreitzer** [comment]
I could use some help with the "CI / e2e-shared-server (pull_request)" failure.

I am not clear on what is going wrong.  I do not know whether it is a failure in the subject of the test or in the test harness.

I do not know how to retry.  It is not prow.

**Comment by sttts** [comment]
Retesting to see whether it is just a flake.

**Comment by MikeSpreitzer** [comment]
The real deal is #2966

**Pull request closed without merging**
