### PR TITLE
Use authorization.WorkspaceAcccessNotPermittedReason

### PR DESCRIPTION
**Pull request by sttts**
We got some more places where a custom string was used.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Checks don't seem to want to run for this one, weird.

**Comment by stevekuznetsov** [comment]
Can manually merge when prow is green I guess

**Comment by stevekuznetsov** [comment]
@sttts looks like you broke a lot of tests :)

**Comment by stevekuznetsov** [comment]
oops

/reopen

**Comment by sttts** [comment]
Fixed unit test.

**Pull request merged**
