### PR TITLE
:bug: admission/webhooks: set kcp.io/cluster annotation on create

### PR DESCRIPTION
**Pull request by sttts**
## Summary

On webhook admission on create, it is unclear where the object comes from. This PR sets the `kcp.io/cluster` annotation on webhook dispatch.

## Release Notes

```release-note
Set the kcp.io/cluster annotation on objects passed to an admission webhook on create.
```

### CODE REVIEW

**Comment by mjudeikis** [comment]
/lgtm
/approve
tests are red but code looks ok

**Comment by sttts** [comment]
Infra.

/retest

**Pull request merged**
