### PR TITLE
🐛 kcp: make BindRootAPIs method more resilient

### PR DESCRIPTION
**Pull request by p0lyn0mial**
## Summary
previously a single error could have stopped the server from becoming ready. The following log shows that it happened when an APIExpor was updated before `BindRootAPIs` got a chance to execute its update.

Thus this PR makes the method more resilient to errors by retrying in a loop. It follows the same pattern we already use for methods in `config/helpers/bootstrap.go` pkg.

I was seeing `server.go:196] "failed to bootstrap root workspace phase 0" err="could not update API binding root|shards.tenancy.kcp.dev: Operation cannot be fulfilled on apibindings.apis.kcp.dev \"shards.tenancy.kcp.dev\": the object has been modified; please apply your changes to the latest version and try again" component="kcp" postStartHook="kcp-start-informers"`

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Doesn't this dupe https://github.com/kcp-dev/kcp/pull/2307

**Comment by p0lyn0mial** [comment]
> Doesn't this dupe https://github.com/kcp-dev/kcp/pull/2307

eh, I was first :P

**Comment by p0lyn0mial** [comment]
> Doesn't this dupe https://github.com/kcp-dev/kcp/pull/2307

plus mine also converts config/helpers/bootstrap.go to contextual logging :)

**Comment by p0lyn0mial** [comment]
/hold

note sure which one gets merged first.

**Comment by stevekuznetsov** [comment]
This is a couple days after the other one, not sure what "first" means ;)

The code here

/lgtm
/approve
/hold

@ncdc any reason we should prefer yours?

**Pull request closed without merging**
